services:
  server:
    build:
      context: .
      dockerfile: server.dockerfile
    container_name: server
    depends_on:
      - mongo
    volumes:
      - ./var/docker/server:/solution/projects/server/var
    restart: unless-stopped
    ports:
      - 9151:9151

  client:
    build:
      context: .
      dockerfile: client.dockerfile
    container_name: client
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - 9150:80

  mongo:
    image: mongo
    container_name: focus-mongo
    restart: unless-stopped
    volumes:
      - ./var/docker/mongo:/data/db
    ports:
      - 9152:27017

