export t
export args

run: 
	yarn run dev --port 3000

lint:
	npx eslint --fix $(args) src/$(t)

tailwind.build:
	npx tailwind -i src/main.css -o src/tailwind.css --minify

tailwind.build-watch:
	npx tailwind -i src/main.css -o src/tailwind.css --watch --minify

