export t
export args

run:
	ng serve --port 9050

lint:
	npx eslint --fix $(args) src/$(t)

# tailwind.build:
# 	npx tailwind -i src/main.css -o src/tailwind.css --minify

# tailwind.build-watch:
# 	npx tailwind -i src/main.css -o src/tailwind.css --watch --minify

